locations:
  home:
    geo_terms:
    - Harper's Ferry
    - Jefferson County
    - Jefferson County County
    - WV
    - West Virginia
    wiki_pages:
    - harpers-ferry
    - i-81
    - jefferson-county-county-west-virginia
    - us-340
    roads:
    - I-81
    - US-340
    metadata:
      city: Harper's Ferry
      county: Jefferson County
      state: West Virginia
      state_code: WV
  work:
    geo_terms:
    - Frederick
    - Frederick County
    - Frederick County County
    - MD
    - Maryland
    wiki_pages:
    - frederick
    - frederick-county-county-maryland
    - i-70
    - us-15
    roads:
    - I-70
    - US-15
    metadata:
      city: Frederick
      county: Frederick County
      state: Maryland
      state_code: MD
union:
  geo_terms:
  - Frederick
  - Frederick County
  - Frederick County County
  - Harper's Ferry
  - Jefferson County
  - Jefferson County County
  - MD
  - Maryland
  - WV
  - West Virginia
  wiki_pages:
  - frederick
  - frederick-county-county-maryland
  - harpers-ferry
  - i-70
  - i-81
  - jefferson-county-county-west-virginia
  - us-15
  - us-340
  roads:
  - I-70
  - I-81
  - US-15
  - US-340
  metadata: {}
